# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EMNewton0 <- function(maxiterEM, tolEM, alpha, zeta, x, delta, t, tevent, num_class, d, lambda_EM, loglik_EM, postweight, printplot) {
    .Call(`_LCAtoolbox_EMNewton0`, maxiterEM, tolEM, alpha, zeta, x, delta, t, tevent, num_class, d, lambda_EM, loglik_EM, postweight, printplot)
}

EMNewton <- function(maxiterEM, tolEM, maxiterNewton, tolNewton, alpha, zeta, x, delta, t, tevent, num_class, d, tau, lambda_EM, loglik_EM, postweight, printplot) {
    .Call(`_LCAtoolbox_EMNewton`, maxiterEM, tolEM, maxiterNewton, tolNewton, alpha, zeta, x, delta, t, tevent, num_class, d, tau, lambda_EM, loglik_EM, postweight, printplot)
}

LinProjCpp <- function(mu, v, gamma, phi, id, obs, time, y) {
    .Call(`_LCAtoolbox_LinProjCpp`, mu, v, gamma, phi, id, obs, time, y)
}

newton <- function(maxiterNewton, tolNewton, alpha, zeta, x, delta, t, tevent, num_class, tau, lambda_EM, loglik_EM) {
    .Call(`_LCAtoolbox_newton`, maxiterNewton, tolNewton, alpha, zeta, x, delta, t, tevent, num_class, tau, lambda_EM, loglik_EM)
}

lambda_EM <- function(zeta, x, t, tevent, num_class, tau) {
    .Call(`_LCAtoolbox_lambda_EM`, zeta, x, t, tevent, num_class, tau)
}

loglik_EM <- function(alpha, zeta, x, delta, t, tevent, num_class, d, d1, d2, tau) {
    .Call(`_LCAtoolbox_loglik_EM`, alpha, zeta, x, delta, t, tevent, num_class, d, d1, d2, tau)
}

numericInfo <- function(alpha, zeta, x, delta, t, tevent, num_class, l0, tau, epsilon, lambda_EM, loglik_EM, postweight) {
    .Call(`_LCAtoolbox_numericInfo`, alpha, zeta, x, delta, t, tevent, num_class, l0, tau, epsilon, lambda_EM, loglik_EM, postweight)
}

postweight <- function(alpha, zeta, x, delta, t, tevent, num_class, d) {
    .Call(`_LCAtoolbox_postweight`, alpha, zeta, x, delta, t, tevent, num_class, d)
}

varestcpp <- function(zeta, delta, chaz, tau, p, x, tevent) {
    .Call(`_LCAtoolbox_varestcpp`, zeta, delta, chaz, tau, p, x, tevent)
}

varestcpp_sltca <- function(t0, x, y, tau, p, Y_dist, id, mu, lbeta, covgee, phi, gamma) {
    .Call(`_LCAtoolbox_varestcpp_sltca`, t0, x, y, tau, p, Y_dist, id, mu, lbeta, covgee, phi, gamma)
}

